name: Pithos
markdown: redcarpet
pygments: true
baseurl: 'http://pithos.io'
nav:
  - name: Quickstart
    target: /quickstart/
  - name: Design
    target: /design/
  - name: Reference
    target: /reference/
  - name: Support
    target: /support/
  - name: <i class="fa fa-github"></i> GitHub
    target: https://github.com/exoscale/pithos

feature_config:
  "Ok":
    class: success
    icon: check
  "No":
    class: danger
    icon: times
  "In Progress":
    class: warning
    icon: wrench
  "Incomplete":
    class: warning
    icon: exclamation-triangle

features:
  - name: Authorization
    status: Ok
    notes: Ability to masquerade as tenant for master key holders. Identity management is pluggable.
  - name: Storage Classes
    status: Ok
    notes: Ability to masquerade as tenant for master key holders.
  - name: Bucket Listing
    status: Ok
  - name: Bucket Creation
    status: Ok
  - name: Bucket Deletion
    status: Ok
  - name: Bucket Info
    status: Ok
  - name: Bucket Location
    status: Ok
  - name: Bucket ACLs
    status: In Progress
  - name: Bucket CORS
    status: In Progress
  - name: Bucket Versioning
    status: Incomplete
    notes: Object stored versioned but no way to retrieve previous versions yet.
  - name: Bucket Policy
    status: "No"
    notes: ACLs cover our needs.
  - name: Bucket Logging
    status: "No"
    notes: Makes no sense yet in our case.
  - name: Bucket Lifecycle
    status: "No"
    notes: Dummy requests and responses supported for client compatibility
  - name: Bucket Requester Pays
    status: "No"
    notes: Makes no sense yet in our case.
  - name: Bucket Website
    status: "No"
    notes: Need a DNS infrastructure. Hosting assets is possible.
  - name: Object Creation
    status: Ok
  - name: Object Deletion
    status: Ok
  - name: Object Multipart Uploads
    status: Ok
  - name: Object ACLs
    status: Ok
    notes: Public ACLs supported
  - name: Object Torrent
    status: "No"
