version: '2'
services:
  pithos:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
    links:
      - cassandra
    volumes:
      - ./:/pithos
  cassandra:
    image: cassandra:2.1
